from __future__ import annotations

from pathlib import Path

from .model.document import LayoutDocument


def export_python_script(document: LayoutDocument, path: str) -> str:
    """Generates a standalone Python script that recreates this layout via
    direct gdsfactory calls — for keeping the design as reviewable,
    version-controllable code, alongside (not instead of) the editable
    `.phidler` project file and the flattened GDS export.

    Reuses the exact same data save_project does (component_spec + kwargs
    + transform for instances; port pairs + cross_section for routes) —
    just emitted as Python source instead of JSON, so it stays consistent
    with how the rest of this app already thinks about a design's recipe.
    """
    s = document.project_settings
    lines: list[str] = [
        '"""Auto-generated by Phidler — recreates this layout via direct gdsfactory calls.',
        "",
        "Project settings (metadata only — does not affect the generated geometry).",
        "One 'key: value' per line so File > Open can parse this back reliably —",
        "see import_script.py. Reformatting this block breaks that, harmlessly:",
        "settings just fall back to defaults, same as a project with no settings at all.",
        f"platform_name: {s.platform_name}",
        f"core_index: {s.core_index}",
        f"clad_index: {s.clad_index}",
        f"thickness_um: {s.thickness_um}",
        f"wavelength_um: {s.wavelength_um}",
        f"cross_section: {s.cross_section}",
        '"""',
        "",
        "import gdsfactory as gf",
        "import klayout.db as kdb",
        "from gdsfactory.gpdk import get_generic_pdk",
        "",
        "get_generic_pdk().activate()",
        "",
    ]

    if document.custom_component_paths:
        lines.append("# This design uses custom components — register them with the PDK first.")
        lines.append("from phidler.custom_components import load_custom_components")
        lines.append("")
        for custom_path in document.custom_component_paths:
            lines.append(f"load_custom_components({custom_path!r})")
        lines.append("")

    lines.append("top = gf.Component()")
    lines.append("")

    var_names: dict[int, str] = {}
    if document.instances:
        lines.append("# --- instances ---")
        for inst in document.instances.values():
            var_name = f"inst_{inst.id}"
            var_names[inst.id] = var_name
            kwargs_str = ", ".join(f"{key}={value!r}" for key, value in inst.kwargs.items())
            call = f"gf.get_component({inst.component_spec!r}" + (f", {kwargs_str}" if kwargs_str else "") + ")"
            transform = document.get_transform(inst.id)
            array = inst.array
            array_str = (
                f", columns={array.columns!r}, rows={array.rows!r}, "
                f"column_pitch={array.column_pitch!r}, row_pitch={array.row_pitch!r}"
                if array.is_array
                else ""
            )
            lines.append(f"{var_name} = top.add_ref({call}{array_str})")
            lines.append(
                f"{var_name}.dcplx_trans = kdb.DCplxTrans("
                f"{transform.mag!r}, {transform.rotation!r}, {transform.mirror!r}, {transform.x!r}, {transform.y!r})"
            )
        lines.append("")

    if document.routes:
        lines.append("# --- routes ---")
        for route in document.routes.values():
            a_var = var_names.get(route.instance_id_a)
            b_var = var_names.get(route.instance_id_b)
            if a_var is None or b_var is None:
                lines.append(f"# skipped route #{route.id}: an endpoint instance no longer exists")
                continue
            # Auto-matched routes carry a meander; emit its steps so the
            # standalone script reproduces the length-matched geometry rather
            # than a shorter natural route.
            steps = document.meander_steps_for_route(route)
            steps_arg = f", steps={steps!r}" if steps else ""
            if route.goal_length_um:
                lines.append(f"# route #{route.id} goal length: {route.goal_length_um:.4f} µm")
            lines.append(
                f"gf.routing.route_single(top, {a_var}.ports[{route.port_name_a!r}], "
                f"{b_var}.ports[{route.port_name_b!r}], cross_section={route.cross_section!r}{steps_arg})"
            )
        lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    import pathlib")
    lines.append("")
    lines.append("    gds_path = pathlib.Path(__file__).with_suffix('.gds')")
    lines.append("    top.write_gds(str(gds_path))")
    lines.append("    print(f'Wrote {gds_path}')")
    lines.append("")

    script = "\n".join(lines)
    Path(path).write_text(script)
    return script
